### ISSUE TITLE
Argument Error

### ISSUE THREAD

**Issue by gimmy** [Manitary/PDF-Metadata-Editor#2]
![ErrorPDF-metadata](https://user-images.githubusercontent.com/1421027/201860353-524948a2-d2e1-41bb-8c4e-2ed4cf2c6771.png)

To reproduce:
Open a PDF with the software, modify some metadata, save, close. (Remove the `_backup` file if you wish).
Reopening the new modified PDF gives the error.

This prevents further modifications of the metadata of the same file.

**Comment by Manitary** [comment]
Since I cannot reproduce the issue with the Python script nor its executable version, I added a logging option to make errors easier to trace.
The version in the develop branch should work, you can manually toggle logging from the GUI or passing the argument -d when running the script.
When changing logging level from the GUI, the setting should be stored on your system; the option -d will override the setting but not overwrite it.

Currently, it only catches errors when trying to either open a file or save changes; such errors will generate a log entry except when trying to open a password-protected file or to alter a file that already has a backup.
Log entries are stored in a log/ folder created from where the program is run, and are stored with a timestamp of when the session was started.
